# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtGui import QPixmap, QPalette
from PyQt5.QtCore import Qt#设置背景色

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(950, 600)
        self.label_ori = QtWidgets.QLabel(Dialog)
        self.label_ori.setGeometry(QtCore.QRect(20, 75, 560, 420))
        self.label_ori.setText("")
        self.label_ori.setObjectName("label_ori")
        # self.pushButton_Model = QtWidgets.QPushButton(Dialog)
        # self.pushButton_Model.setGeometry(QtCore.QRect(20, 140, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        # self.pushButton_Model.setFont(font)
        # self.pushButton_Model.setObjectName("pushButton_Model")
        self.pushButton_Exit = QtWidgets.QPushButton(Dialog)
        self.pushButton_Exit.setGeometry(QtCore.QRect(620, 15, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.label_det = QtWidgets.QLabel(Dialog)
        self.label_det.setGeometry(QtCore.QRect(370, 215, 320, 240))
        self.label_det.setText("")
        self.label_det.setObjectName("label_det")
        self.pushButton_Img = QtWidgets.QPushButton(Dialog)
        self.pushButton_Img.setGeometry(QtCore.QRect(20, 15, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Img.setFont(font)
        self.pushButton_Img.setObjectName("pushButton_Img")
        # self.pushButton_ImgFolder = QtWidgets.QPushButton(Dialog)
        # self.pushButton_ImgFolder.setGeometry(QtCore.QRect(140, 140, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        # self.pushButton_ImgFolder.setFont(font)
        # self.pushButton_ImgFolder.setObjectName("pushButton_ImgFolder")
        # self.pushButton_Video = QtWidgets.QPushButton(Dialog)
        # self.pushButton_Video.setGeometry(QtCore.QRect(140, 20, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        # self.pushButton_Video.setFont(font)
        # self.pushButton_Video.setObjectName("pushButton_Video")
        self.pushButton_Camera = QtWidgets.QPushButton(Dialog)
        self.pushButton_Camera.setGeometry(QtCore.QRect(140, 15, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Camera.setFont(font)
        self.pushButton_Camera.setObjectName("pushButton_Camera")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(600, 495, 800, 100))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(700, 515, 210, 40))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_BegDet = QtWidgets.QPushButton(Dialog)
        self.pushButton_BegDet.setGeometry(QtCore.QRect(260, 15, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_BegDet.setFont(font)
        self.pushButton_BegDet.setObjectName("pushButton_BegDet")
        self.pushButton_StopDet = QtWidgets.QPushButton(Dialog)
        self.pushButton_StopDet.setGeometry(QtCore.QRect(380, 15, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_StopDet.setFont(font)
        self.pushButton_StopDet.setObjectName("pushButton_StopDet")
        self.pushButton_SavePath = QtWidgets.QPushButton(Dialog)
        self.pushButton_SavePath.setGeometry(QtCore.QRect(500, 15, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_SavePath.setFont(font)
        self.pushButton_SavePath.setObjectName("pushButton_SavePath")

        #设置数据层次结构，4行4列
        self.ItemModel=QStandardItemModel(10,3)
        #设置水平方向四个头标签文本内容
        self.ItemModel.setHorizontalHeaderLabels(['垃圾类别','垃圾数量','分类成功'])

        for row in range(10):
            for column in range(3):
                item = QStandardItem('%s'%(0))
                item.setTextAlignment(Qt.AlignCenter)      # 设置文本居中
                #设置每个位置的文本值
                self.ItemModel.setItem(row,column,item)

        #实例化表格视图，设置模型为自定义的模型
        self.tableView=QTableView(Dialog)
        self.tableView.setModel(self.ItemModel)
        self.tableView.setGeometry(QtCore.QRect(600, 75, 330, 420))

        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(600, 75, 330, 420))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(15)
        item = QtWidgets.QTableWidgetItem('垃圾类别')
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem('垃圾数量')
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem('分类成功')
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.label_kehuishou = QtWidgets.QLabel(Dialog)
        self.label_kehuishou.setGeometry(QtCore.QRect(20, 515, 150, 40))
        self.label_kehuishou.setText("可回收垃圾状态")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_kehuishou.setFont(font)
        self.bin_kehuishou = QtWidgets.QLabel(Dialog)
        self.bin_kehuishou.setAutoFillBackground(True)
        palette_green = QPalette()
        palette_green.setColor(QPalette.Window, Qt.green)
        self.bin_kehuishou.setPalette(palette_green)
        self.bin_kehuishou.setGeometry(QtCore.QRect(165, 32+495, 20, 20))
        self.bin_kehuishou.setText("")

        self.label_chuyu = QtWidgets.QLabel(Dialog)
        self.label_chuyu.setGeometry(QtCore.QRect(205, 20+495, 150, 40))
        self.label_chuyu.setText("厨余垃圾状态")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_chuyu.setFont(font)
        self.bin_chuyu = QtWidgets.QLabel(Dialog)
        self.bin_chuyu.setAutoFillBackground(True)
        palette_green = QPalette()
        palette_green.setColor(QPalette.Window, Qt.green)
        self.bin_chuyu.setPalette(palette_green)
        self.bin_chuyu.setGeometry(QtCore.QRect(330, 32+495, 20, 20))
        self.bin_chuyu.setText("")

        self.label_youhai = QtWidgets.QLabel(Dialog)
        self.label_youhai.setGeometry(QtCore.QRect(370, 20+495, 150, 40))
        self.label_youhai.setText("有害垃圾状态")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_youhai.setFont(font)
        self.bin_youhai = QtWidgets.QLabel(Dialog)
        self.bin_youhai.setAutoFillBackground(True)
        palette_green = QPalette()
        palette_green.setColor(QPalette.Window, Qt.green)
        self.bin_youhai.setPalette(palette_green)
        self.bin_youhai.setGeometry(QtCore.QRect(495, 32+495, 20, 20))
        self.bin_youhai.setText("")

        self.label_qita = QtWidgets.QLabel(Dialog)
        self.label_qita.setGeometry(QtCore.QRect(535, 20+495, 150, 40))
        self.label_qita.setText("其他垃圾状态")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_qita.setFont(font)
        self.bin_qita = QtWidgets.QLabel(Dialog)
        self.bin_qita.setAutoFillBackground(True)
        palette_green = QPalette()
        palette_green.setColor(QPalette.Window, Qt.green)
        self.bin_qita.setPalette(palette_green)
        self.bin_qita.setGeometry(QtCore.QRect(660, 32+495, 20, 20))
        self.bin_qita.setText("")
        #
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "YOLO-PYQT"))
        # self.pushButton_Model.setText(_translate("Dialog", "选择模型"))
        self.pushButton_Exit.setText(_translate("Dialog", "退出"))
        self.pushButton_Img.setText(_translate("Dialog", "打开图片"))
        # self.pushButton_ImgFolder.setText(_translate("Dialog", "打开文件夹"))
        # self.pushButton_Video.setText(_translate("Dialog", "打开视频"))
        self.pushButton_Camera.setText(_translate("Dialog", "打开摄像头"))
        # self.label.setText(_translate("Dialog", "Title"))
        self.pushButton_BegDet.setText(_translate("Dialog", "开始检测"))
        self.pushButton_StopDet.setText(_translate("Dialog", "停止检测"))
        self.pushButton_SavePath.setText(_translate("Dialog", "宣传片"))

